name: Deploy Api Skripsi
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  web-deploy:
    name: 🎉 Deploy Api Skripsi
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        
      - name: 🌟 Run server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/zidaneali/SkripsiAPI
            git pull
            pip install -r requirements.txt --no-cache-dir
            pm2 restart BE
